language: python
matrix:
  include:
    - python: "3.5"
      env: TOXENV=py35

sudo: false # use container based infrastructure - not sure if this option is good or not

install:
  - pip install tox

script:
  tox
